kumuluzee:
  name: backend-service
  version: 1.0.0-SNAPSHOT
  env:
    prod: false
    name: dev
  server:
    show-server-info: false
    base-url: http://localhost:8080
  cors-filter:
    servlet:
      allow-origin: "*"
      supported-methods: "GET, POST, PUT, PATCH, DELETE, OPTIONS, HEAD"
      exposed-headers: "X-Total-Count,Content-Disposition"
  openapi:
    enabled: true
    ui:
      enabled: true
  logs:
    loggers:
      - name: ''
        level: INFO
  health:
    servlet:
      mapping: /health/
      enabled: true
    checks:
      data-source-health-check:
        type: liveness
        jndi-name: jdbc/mainDB
      disk-space-health-check:
        threshold: 100000000
        type: liveness
      http-health-check:
        connection-url: https://keycloak.mjamsek.com/auth
  rest-client:
    disable-jetty-www-auth: true
  datasources:
    - jndi-name: jdbc/mainDB
      connection-url: jdbc:postgresql://localhost:5432/fri-pointer
      username: postgres
      password: postgres
      pool:
        max-size: 20
keycloak:
  realm: fri-pointer
  auth-server-url: https://keycloak.mjamsek.com/auth
  client-id: backend-service
  auth:
    client-secret: not_set
upload:
  s3:
    bucket: fri-pointer-data
    upload-endpoint: https://fri-pointer-data.s3-accelerate.amazonaws.com
    public-endpoint: https://fri-pointer-data.s3.eu-central-1.amazonaws.com
    access-key-id: not_set
    secret-access-key: not_set