sudo: required

services:
  - docker

language: java
dist: trusty

branches:
  only:
    - develop
    - master

jdk:
  - openjdk11

cache:
  directories:
    - "$HOME/.m2"

install: echo "Skipping installation"

script:
  - mvn clean package -DskipTests=true --settings .ci/settings.xml
  - docker build -t fri-pointer/backend-service .

after_success:
  - mvn deploy -DskipTests=true --settings .ci/settings.xml -P !default,deploy-lib
#  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
#  - docker push fri-pointer/backend-service

